sudo: required
services:
  - docker

before_install:
  - docker build -t kunalhemrajani/docker-react-sample-deployment -f Dockerfile.dev .

script:
  - docker run kunalhemrajani/docker-react-sample-deployment npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "docker-react-sample-deployment"
  env: "DockerReactSampleDeployment-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-624295586661"
  bucket_path: "docker-react-sample-deployment"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"